import type { ElementType, ParamDef } from './types';

export interface ElementDef {
  label: string;
  icon: string;
  description: string;
  defaults: Record<string, any>;
  params: ParamDef[];
}

const FONTS = [
  'Helvetica, Arial, sans-serif',
  'Georgia, serif',
  '"Courier New", monospace',
  '"Trebuchet MS", sans-serif',
  'Impact, sans-serif',
  '"Comic Sans MS", cursive',
];

const POSITION: ParamDef[] = [
  { key: 'x', label: 'X', kind: 'number', min: -1000, max: 5000, step: 1 },
  { key: 'y', label: 'Y', kind: 'number', min: -1000, max: 4000, step: 1 },
];

export const ELEMENTS: Record<ElementType, ElementDef> = {
  text: {
    label: 'Text',
    icon: '🅣',
    description: 'A text layer',
    defaults: {
      text: 'Hello world',
      fontSize: 90,
      color: '#ffffff',
      fontFamily: FONTS[0],
      fontWeight: 700,
      letterSpacing: 0,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'text', label: 'Text', kind: 'text' },
      { key: 'fontSize', label: 'Font size', kind: 'number', min: 8, max: 600, step: 1 },
      { key: 'color', label: 'Color', kind: 'color' },
      { key: 'fontFamily', label: 'Font', kind: 'select', options: FONTS },
      { key: 'fontWeight', label: 'Weight', kind: 'select', options: ['300', '400', '500', '700', '900'] },
      { key: 'letterSpacing', label: 'Letter spacing', kind: 'number', min: -10, max: 60, step: 0.5 },
      { key: 'textureSrc', label: 'Letter fill — image URL or CSS gradient(…)', kind: 'text' },
      ...POSITION,
    ],
  },
  counter: {
    label: 'Counter',
    icon: '🔢',
    description: 'A number that counts from A to B over the clip',
    defaults: {
      from: 0,
      to: 100,
      decimals: 0,
      prefix: '',
      suffix: '%',
      fontSize: 120,
      color: '#ffffff',
      fontFamily: FONTS[0],
      fontWeight: 700,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'from', label: 'Count from', kind: 'number', min: -1000000, max: 1000000, step: 1 },
      { key: 'to', label: 'Count to', kind: 'number', min: -1000000, max: 1000000, step: 1 },
      { key: 'decimals', label: 'Decimals', kind: 'number', min: 0, max: 4, step: 1 },
      { key: 'prefix', label: 'Prefix', kind: 'text' },
      { key: 'suffix', label: 'Suffix', kind: 'text' },
      { key: 'fontSize', label: 'Font size', kind: 'number', min: 8, max: 600, step: 1 },
      { key: 'color', label: 'Color', kind: 'color' },
      { key: 'fontFamily', label: 'Font', kind: 'select', options: FONTS },
      { key: 'fontWeight', label: 'Weight', kind: 'select', options: ['300', '400', '500', '700', '900'] },
      ...POSITION,
    ],
  },
  shape: {
    label: 'Shape',
    icon: '⬛',
    description: 'Rect, circle, ellipse, triangle, star, polygon or pie',
    defaults: {
      kind: 'rect',
      width: 300,
      height: 300,
      fill: '#7c5cff',
      borderRadius: 24,
      points: 5,
      innerRatio: 0.5,
      progress: 0.75,
      direction: 'up',
      rotation: 0,
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      {
        key: 'kind',
        label: 'Shape',
        kind: 'select',
        options: ['rect', 'circle', 'ellipse', 'triangle', 'star', 'polygon', 'pie'],
      },
      { key: 'width', label: 'Width', kind: 'number', min: 4, max: 4000, step: 1 },
      { key: 'height', label: 'Height', kind: 'number', min: 4, max: 4000, step: 1 },
      { key: 'fill', label: 'Fill', kind: 'color' },
      { key: 'borderRadius', label: 'Corner radius (rect)', kind: 'number', min: 0, max: 500, step: 1 },
      { key: 'points', label: 'Points (star/polygon)', kind: 'number', min: 3, max: 12, step: 1 },
      { key: 'innerRatio', label: 'Inner radius (star)', kind: 'number', min: 0.1, max: 0.9, step: 0.05 },
      { key: 'progress', label: 'Progress (pie)', kind: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'direction', label: 'Direction (triangle)', kind: 'select', options: ['up', 'down', 'left', 'right'] },
      { key: 'rotation', label: 'Rotation', kind: 'number', min: -360, max: 360, step: 1 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  image: {
    label: 'Image',
    icon: '🖼️',
    description: 'An image from a URL',
    defaults: {
      src: 'https://picsum.photos/seed/remotion/800/600',
      width: 600,
      height: 450,
      borderRadius: 16,
      objectFit: 'cover',
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'src', label: 'Image URL', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'height', label: 'Height', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'borderRadius', label: 'Corner radius', kind: 'number', min: 0, max: 500, step: 1 },
      { key: 'objectFit', label: 'Fit', kind: 'select', options: ['cover', 'contain', 'fill'] },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  video: {
    label: 'Video',
    icon: '🎥',
    description: 'A video from a URL (mp4/webm)',
    defaults: {
      src: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      width: 960,
      height: 540,
      borderRadius: 0,
      objectFit: 'cover',
      volume: 1,
      playbackRate: 1,
      startFrom: 0,
      muted: 'no',
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'src', label: 'Video URL', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'height', label: 'Height', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'borderRadius', label: 'Corner radius', kind: 'number', min: 0, max: 500, step: 1 },
      { key: 'objectFit', label: 'Fit', kind: 'select', options: ['cover', 'contain', 'fill'] },
      { key: 'volume', label: 'Volume', kind: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'playbackRate', label: 'Speed', kind: 'number', min: 0.25, max: 4, step: 0.05 },
      { key: 'startFrom', label: 'Trim start (frames)', kind: 'number', min: 0, max: 100000, step: 1 },
      { key: 'muted', label: 'Muted', kind: 'select', options: ['no', 'yes'] },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  audio: {
    label: 'Audio',
    icon: '🎵',
    description: 'Music or sound from a URL (mp3/wav)',
    defaults: {
      src: '',
      volume: 1,
      playbackRate: 1,
      startFrom: 0,
    },
    params: [
      { key: 'src', label: 'Audio URL', kind: 'text' },
      { key: 'volume', label: 'Volume', kind: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'playbackRate', label: 'Speed', kind: 'number', min: 0.25, max: 4, step: 0.05 },
      { key: 'startFrom', label: 'Trim start (frames)', kind: 'number', min: 0, max: 100000, step: 1 },
    ],
  },
  gif: {
    label: 'GIF',
    icon: '🎞️',
    description: 'An animated GIF, synced to the timeline',
    defaults: {
      src: 'https://media.giphy.com/media/3o7aCSPqXE5C6T8tBC/giphy.gif',
      width: 480,
      height: 360,
      fit: 'contain',
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'src', label: 'GIF URL', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'height', label: 'Height', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'fit', label: 'Fit', kind: 'select', options: ['contain', 'cover', 'fill'] },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  html: {
    label: 'HTML',
    icon: '🧩',
    description: 'Any HTML + inline CSS — chat mockups, app windows, cards (HyperFrames-style)',
    defaults: {
      html: '<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:#1c1f28;border:1px solid #333;border-radius:24px;color:#fff;font-family:Helvetica,Arial,sans-serif;font-size:42px">Paste any HTML here</div>',
      width: 800,
      height: 500,
      contentScale: 1,
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'html', label: 'HTML (inline styles recommended)', kind: 'textarea' },
      { key: 'width', label: 'Width', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'height', label: 'Height', kind: 'number', min: 10, max: 4000, step: 1 },
      { key: 'contentScale', label: 'Content scale', kind: 'number', min: 0.1, max: 4, step: 0.05 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  cursor: {
    label: 'Cursor',
    icon: '🖱️',
    description: 'A mouse pointer for UI-demo storytelling — pair with Motion Path + Click Pulse',
    defaults: { size: 56, color: '#ffffff', x: 960, y: 540 },
    params: [
      { key: 'size', label: 'Size', kind: 'number', min: 12, max: 300, step: 1 },
      { key: 'color', label: 'Fill', kind: 'color' },
      ...POSITION,
    ],
  },
  wave: {
    label: 'Wave',
    icon: '🌊',
    description: 'Layered animated sine waves — great for footers and water',
    defaults: {
      width: 1920,
      height: 400,
      color: '#35c4ff',
      amplitude: 55,
      wavelength: 480,
      speed: 0.5,
      layers: 3,
      opacity: 0.9,
      x: 960,
      y: 900,
    },
    params: [
      { key: 'width', label: 'Width', kind: 'number', min: 100, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 40, max: 2000, step: 10 },
      { key: 'color', label: 'Color', kind: 'color' },
      { key: 'amplitude', label: 'Amplitude', kind: 'number', min: 2, max: 400, step: 1 },
      { key: 'wavelength', label: 'Wavelength', kind: 'number', min: 40, max: 2000, step: 10 },
      { key: 'speed', label: 'Speed (Hz)', kind: 'number', min: -4, max: 4, step: 0.05 },
      { key: 'layers', label: 'Layers', kind: 'number', min: 1, max: 5, step: 1 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  blob: {
    label: 'Blob',
    icon: '🫧',
    description: 'Organic morphing blob — stack a few for a fluid / splat look',
    defaults: {
      size: 420,
      color: '#7c5cff',
      wobble: 0.35,
      speed: 0.5,
      points: 8,
      seed: 'blob-1',
      opacity: 0.9,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'size', label: 'Size', kind: 'number', min: 20, max: 3000, step: 10 },
      { key: 'color', label: 'Color', kind: 'color' },
      { key: 'wobble', label: 'Wobble', kind: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'speed', label: 'Morph speed', kind: 'number', min: 0, max: 4, step: 0.05 },
      { key: 'points', label: 'Points', kind: 'number', min: 4, max: 16, step: 1 },
      { key: 'seed', label: 'Seed (any text)', kind: 'text' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  particles: {
    label: 'Particles',
    icon: '🎊',
    description: 'Confetti, snow, rain, sparkles, bubbles or embers',
    defaults: {
      kind: 'confetti',
      count: 80,
      width: 1920,
      height: 1080,
      size: 14,
      speed: 1,
      drift: 30,
      colors: '#7c5cff,#35c4ff,#ff5c6c,#ffd166,#6ee7a8',
      imageSrc: '',
      seed: 'party',
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      {
        key: 'kind',
        label: 'Type',
        kind: 'select',
        options: ['confetti', 'snow', 'rain', 'sparkles', 'bubbles', 'embers', 'scatter'],
      },
      { key: 'count', label: 'Count', kind: 'number', min: 5, max: 300, step: 5 },
      { key: 'width', label: 'Area width', kind: 'number', min: 100, max: 8000, step: 10 },
      { key: 'height', label: 'Area height', kind: 'number', min: 100, max: 4000, step: 10 },
      { key: 'size', label: 'Particle size', kind: 'number', min: 2, max: 120, step: 1 },
      { key: 'speed', label: 'Speed', kind: 'number', min: 0.1, max: 6, step: 0.1 },
      { key: 'drift', label: 'Sideways drift (px)', kind: 'number', min: 0, max: 300, step: 5 },
      { key: 'colors', label: 'Colors (comma-separated)', kind: 'text' },
      { key: 'imageSrc', label: 'PNG/SVG particle image (optional)', kind: 'text' },
      { key: 'seed', label: 'Seed (any text)', kind: 'text' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  synthGrid: {
    label: 'Synth Grid',
    icon: '🛣️',
    description: 'Endless-outrun perspective grid floor, scrolling forever',
    defaults: {
      width: 1920,
      height: 520,
      lineColor: '#ff3ea5',
      horizonColor: '#2b0f45',
      spacing: 96,
      speed: 0.8,
      glow: 10,
      opacity: 1,
      x: 960,
      y: 820,
    },
    params: [
      { key: 'width', label: 'Width', kind: 'number', min: 200, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 100, max: 4000, step: 10 },
      { key: 'lineColor', label: 'Line color', kind: 'color' },
      { key: 'horizonColor', label: 'Horizon haze', kind: 'color' },
      { key: 'spacing', label: 'Cell size', kind: 'number', min: 20, max: 400, step: 2 },
      { key: 'speed', label: 'Drive speed (cells/s)', kind: 'number', min: -6, max: 6, step: 0.1 },
      { key: 'glow', label: 'Glow', kind: 'number', min: 0, max: 60, step: 1 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  neonSun: {
    label: 'Neon Sun',
    icon: '🌅',
    description: 'Striped retro sun with glow — the outrun horizon centerpiece',
    defaults: {
      size: 620,
      colorTop: '#ffe94d',
      colorBottom: '#ff3ea5',
      stripes: 7,
      glow: 45,
      opacity: 1,
      x: 960,
      y: 420,
    },
    params: [
      { key: 'size', label: 'Size', kind: 'number', min: 60, max: 3000, step: 10 },
      { key: 'colorTop', label: 'Top color', kind: 'color' },
      { key: 'colorBottom', label: 'Bottom color', kind: 'color' },
      { key: 'stripes', label: 'Stripe count', kind: 'number', min: 0, max: 16, step: 1 },
      { key: 'glow', label: 'Glow', kind: 'number', min: 0, max: 120, step: 1 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  isoCity: {
    label: 'Iso City',
    icon: '🏙️',
    description: 'Generative isometric city that grows building by building',
    defaults: {
      gridSize: 5,
      tileSize: 70,
      buildingHeight: 240,
      stagger: 4,
      colors: '#7c5cff,#35c4ff,#6ee7a8,#ffd166',
      streetColor: '#35c4ff',
      seed: 'metropolis',
      opacity: 1,
      x: 960,
      y: 560,
    },
    params: [
      { key: 'gridSize', label: 'Grid (n×n)', kind: 'number', min: 2, max: 9, step: 1 },
      { key: 'tileSize', label: 'Tile size', kind: 'number', min: 20, max: 200, step: 2 },
      { key: 'buildingHeight', label: 'Max height', kind: 'number', min: 40, max: 800, step: 10 },
      { key: 'stagger', label: 'Growth stagger (frames)', kind: 'number', min: 0, max: 30, step: 0.5 },
      { key: 'colors', label: 'Palette (comma-separated)', kind: 'text' },
      { key: 'streetColor', label: 'Blueprint line color', kind: 'color' },
      { key: 'seed', label: 'Seed (any text)', kind: 'text' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  skyCycle: {
    label: 'Day/Night Sky',
    icon: '🌗',
    description: 'Morphing sky gradient + stars, one full day per clip — pair with Sun & Moon and Ridge',
    defaults: { width: 1920, height: 1080, stars: 90, seed: 'sky', opacity: 1, x: 960, y: 540 },
    params: [
      { key: 'width', label: 'Width', kind: 'number', min: 200, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 100, max: 4000, step: 10 },
      { key: 'stars', label: 'Stars', kind: 'number', min: 0, max: 400, step: 10 },
      { key: 'seed', label: 'Seed (any text)', kind: 'text' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  sunMoon: {
    label: 'Sun & Moon',
    icon: '🌞',
    description: 'Sun and moon arcing across the clip — same day-cycle timing as the Day/Night Sky',
    defaults: {
      width: 1920,
      height: 1080,
      size: 85,
      sunColor: '#ffd93d',
      moonColor: '#e8ecff',
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'width', label: 'Width', kind: 'number', min: 200, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 100, max: 4000, step: 10 },
      { key: 'size', label: 'Sun size', kind: 'number', min: 10, max: 600, step: 5 },
      { key: 'sunColor', label: 'Sun color', kind: 'color' },
      { key: 'moonColor', label: 'Moon color', kind: 'color' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  ridge: {
    label: 'Ridge',
    icon: '⛰️',
    description: 'One seeded mountain silhouette; fill blends day→night over the clip. Stack a few',
    defaults: {
      width: 1920,
      height: 500,
      peaks: 9,
      amplitude: 240,
      baseHeight: 60,
      colorDay: '#39566e',
      colorNight: '#0b0920',
      seed: 'ridge-1',
      opacity: 1,
      x: 960,
      y: 830,
    },
    params: [
      { key: 'width', label: 'Width', kind: 'number', min: 200, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 60, max: 2000, step: 10 },
      { key: 'peaks', label: 'Peaks', kind: 'number', min: 3, max: 24, step: 1 },
      { key: 'amplitude', label: 'Peak height', kind: 'number', min: 20, max: 1500, step: 10 },
      { key: 'baseHeight', label: 'Base height', kind: 'number', min: 0, max: 1000, step: 10 },
      { key: 'colorDay', label: 'Day color', kind: 'color' },
      { key: 'colorNight', label: 'Night color', kind: 'color' },
      { key: 'seed', label: 'Seed (any text)', kind: 'text' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  commitGraph: {
    label: 'Commit Graph',
    icon: '🌿',
    description: 'Animated git history — glowing nodes, branch lanes, typing messages',
    defaults: {
      data: '[{"m":"init repo","b":0,"a":120,"d":0},{"m":"add auth","b":0,"a":340,"d":12},{"m":"feature/timeline","b":1,"a":560,"d":40},{"m":"fix drag bug","b":1,"a":80,"d":22},{"m":"merge timeline","b":0,"a":610,"d":58},{"m":"ship v2.0 🚀","b":0,"a":0,"d":0}]',
      speed: 0.6,
      nodeGap: 300,
      laneColors: '#6ee7a8,#7c5cff,#35c4ff',
      width: 1700,
      height: 500,
      opacity: 1,
      x: 960,
      y: 540,
    },
    params: [
      { key: 'data', label: 'Commits JSON — [{m, b(branch), a(adds), d(dels)}…]', kind: 'textarea' },
      { key: 'speed', label: 'Commits per second', kind: 'number', min: 0.1, max: 5, step: 0.1 },
      { key: 'nodeGap', label: 'Node spacing (px)', kind: 'number', min: 100, max: 800, step: 10 },
      { key: 'laneColors', label: 'Lane colors (comma-separated)', kind: 'text' },
      { key: 'width', label: 'Width', kind: 'number', min: 200, max: 8000, step: 10 },
      { key: 'height', label: 'Height', kind: 'number', min: 100, max: 4000, step: 10 },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  nodeTrail: {
    label: 'Story Trail',
    icon: '📍',
    description: 'Glowing waypoint trail — nodes pop along a route you draw on the canvas',
    defaults: {
      data: '[{"x":0,"y":0,"label":"Start"},{"x":320,"y":-140,"label":"Research","color":"#35c4ff"},{"x":700,"y":60,"label":"Prototype"},{"x":1040,"y":-80,"label":"Launch","color":"#ffd166"},{"x":700,"y":260,"label":"Pivot","color":"#ff5c6c","from":2},{"x":1380,"y":40,"label":"Scale","from":3}]',
      color: '#6ee7a8',
      nodeColor: '#7c5cff',
      speed: 0.8,
      nodeSize: 16,
      lineWidth: 5,
      curved: 'yes',
      fontSize: 30,
      textColor: '#e8eaf0',
      opacity: 1,
      x: 300,
      y: 540,
    },
    params: [
      {
        key: 'data',
        label: 'Waypoints JSON — [{x, y, label?, color?, from?}…]; "from" branches off an earlier node (by index)',
        kind: 'textarea',
      },
      { key: 'color', label: 'Default line color', kind: 'color' },
      { key: 'nodeColor', label: 'Default node color', kind: 'color' },
      { key: 'speed', label: 'Nodes per second', kind: 'number', min: 0.1, max: 5, step: 0.1 },
      { key: 'nodeSize', label: 'Node size', kind: 'number', min: 4, max: 60, step: 1 },
      { key: 'lineWidth', label: 'Line width', kind: 'number', min: 1, max: 20, step: 1 },
      { key: 'curved', label: 'Curved links', kind: 'select', options: ['yes', 'no'] },
      { key: 'fontSize', label: 'Label size', kind: 'number', min: 8, max: 120, step: 1 },
      { key: 'textColor', label: 'Label color', kind: 'color' },
      { key: 'opacity', label: 'Opacity', kind: 'number', min: 0, max: 1, step: 0.01 },
      ...POSITION,
    ],
  },
  emoji: {
    label: 'Emoji',
    icon: '😀',
    description: 'A big emoji sticker',
    defaults: { char: '🚀', size: 160, x: 960, y: 540 },
    params: [
      { key: 'char', label: 'Emoji', kind: 'text' },
      { key: 'size', label: 'Size', kind: 'number', min: 16, max: 1200, step: 1 },
      ...POSITION,
    ],
  },
  background: {
    label: 'Background',
    icon: '🎨',
    description: 'Full-frame solid or gradient fill',
    defaults: { fillType: 'linear', colorA: '#1a1040', colorB: '#4f2d8f', angle: 135 },
    params: [
      { key: 'fillType', label: 'Type', kind: 'select', options: ['solid', 'linear', 'radial'] },
      { key: 'colorA', label: 'Color A', kind: 'color' },
      { key: 'colorB', label: 'Color B', kind: 'color' },
      { key: 'angle', label: 'Angle', kind: 'number', min: 0, max: 360, step: 1 },
    ],
  },
};
